# Generated by Django 3.1.5 on 2021-03-09 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0019_remove_organization_requesters'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientUser',
        ),
    ]
