# Generated by Django 3.1.5 on 2021-01-27 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0004_organization_creatoruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='creatorUser',
        ),
    ]
