# Generated by Django 3.1.5 on 2021-01-27 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0006_organization_creatoruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
