# Generated by Django 3.1.5 on 2021-01-24 04:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder', '0003_auto_20210123_2253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuilderUser',
            new_name='CreatorUser',
        ),
    ]
