# Generated by Django 3.1.5 on 2021-01-27 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_auto_20210126_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatoruser',
            name='organizations',
        ),
    ]
