# Generated by Django 3.1.5 on 2021-01-27 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='creatorUser',
        ),
        migrations.AddField(
            model_name='creatoruser',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='builder.organization'),
            preserve_default=False,
        ),
    ]
