# Generated by Django 3.1.5 on 2021-02-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0011_sheet_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='dateCreated',
            field=models.DateField(default='1970-01-01'),
            preserve_default=False,
        ),
    ]
