# Generated by Django 3.1.5 on 2021-02-23 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0012_sheet_datecreated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='PageListing',
        ),
    ]
