# Generated by Django 3.1.5 on 2021-02-23 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0013_auto_20210222_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dateCreated', models.DateField()),
                ('typee', models.CharField(max_length=30)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.page')),
            ],
        ),
        migrations.RemoveField(
            model_name='sheetitem',
            name='sheet',
        ),
        migrations.DeleteModel(
            name='Sheet',
        ),
        migrations.DeleteModel(
            name='SheetItem',
        ),
    ]
