# Generated by Django 3.1.5 on 2021-02-23 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0014_auto_20210222_2231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageItem',
            new_name='SheetItem',
        ),
    ]
