# Generated by Django 3.1.5 on 2021-03-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0015_auto_20210222_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='membershipRequired',
            field=models.BooleanField(default=False),
        ),
    ]
