# Generated by Django 3.1.5 on 2021-03-09 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0018_organization_requesters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='requesters',
        ),
    ]
