# Generated by Django 3.1.5 on 2021-03-11 22:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder', '0019_remove_organization_requesters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreatorUser',
            new_name='Profile',
        ),
    ]
