# Generated by Django 3.1.5 on 2021-03-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0024_organization_keeper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='keeper',
            new_name='owner',
        ),
    ]
