# Generated by Django 3.1.5 on 2021-03-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0026_organizationapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='memberships',
            field=models.ManyToManyField(related_name='organizationMemberships', to='builder.Organization'),
        ),
    ]
