# Generated by Django 3.1.5 on 2021-03-13 21:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder', '0027_profile_memberships'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationApproval',
            new_name='OrganizationMembershipRequest',
        ),
    ]
