# Generated by Django 3.1.5 on 2021-03-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0029_auto_20210316_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='OrganizationMembershipRequest',
        ),
    ]
