# Generated by Django 3.1.5 on 2021-03-20 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0031_auto_20210316_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetitem',
            name='endDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheetitem',
            name='startDataTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
