# Generated by Django 3.1.5 on 2021-03-24 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0033_auto_20210323_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheetitem',
            old_name='endDateTime',
            new_name='endDatetime',
        ),
        migrations.RenameField(
            model_name='sheetitem',
            old_name='startDateTime',
            new_name='startDatetime',
        ),
    ]
