# Generated by Django 3.1.5 on 2021-03-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0037_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='ProgramItem',
        ),
    ]
