# Generated by Django 3.1.5 on 2021-03-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0038_auto_20210326_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='builder.page')),
                ('description', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100, null=True)),
                ('startDatetime', models.DateTimeField(null=True)),
                ('endDatetime', models.DateTimeField(null=True)),
            ],
            bases=('builder.page',),
        ),
        migrations.DeleteModel(
            name='ProgramItem',
        ),
    ]
