# Generated by Django 3.1.5 on 2021-03-28 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0040_auto_20210327_2010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
