# Generated by Django 3.1.5 on 2021-03-28 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0041_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100, null=True)),
                ('startDatetime', models.DateTimeField(null=True)),
                ('endDatetime', models.DateTimeField(null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.page')),
            ],
        ),
    ]
