# Generated by Django 3.1.5 on 2021-04-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0043_auto_20210328_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendanceIsPublic',
            field=models.BooleanField(default=False),
        ),
    ]
