# Generated by Django 3.1.5 on 2021-04-03 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0045_repeatingoccurence'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeatingoccurence',
            name='sheetItem',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='builder.sheetitem'),
            preserve_default=False,
        ),
    ]
