# Generated by Django 3.1.5 on 2021-04-11 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0046_repeatingoccurence_sheetitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeatingoccurence',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.event'),
        ),
        migrations.AlterField(
            model_name='repeatingoccurence',
            name='sheetItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.sheetitem'),
        ),
    ]
