# Generated by Django 3.1.5 on 2021-04-13 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0047_auto_20210411_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='endDatetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='startDatetime',
        ),
        migrations.RemoveField(
            model_name='sheetitem',
            name='endDatetime',
        ),
        migrations.RemoveField(
            model_name='sheetitem',
            name='startDatetime',
        ),
        migrations.CreateModel(
            name='SingleOccurence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDatetime', models.DateTimeField()),
                ('endDatetime', models.DateTimeField()),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.event')),
                ('sheetItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.sheetitem')),
            ],
        ),
    ]
