# Generated by Django 3.1.5 on 2021-04-14 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0048_auto_20210413_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='private',
            new_name='isPrivate',
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.organization'),
        ),
    ]
