# Generated by Django 3.2 on 2021-05-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0051_page_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='description',
            new_name='explanation',
        ),
    ]
