# Generated by Django 3.2.5 on 2021-07-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0053_page_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='color',
        ),
        migrations.AddField(
            model_name='pagelisting',
            name='color',
            field=models.CharField(default='rgb(231, 231, 231)', max_length=30),
            preserve_default=False,
        ),
    ]
