# Generated by Django 3.2.5 on 2021-07-20 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0054_auto_20210718_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.PositiveSmallIntegerField()),
                ('green', models.PositiveSmallIntegerField()),
                ('blue', models.PositiveSmallIntegerField()),
                ('alpha', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='pagelisting',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.colorfield'),
        ),
    ]
