# Generated by Django 3.2.5 on 2021-07-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0055_auto_20210720_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='headquarters',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
