# Generated by Django 3.2.5 on 2021-07-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0056_organization_headquarters'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='NewOrganizationRequest',
        ),
    ]
