# Generated by Django 3.2.5 on 2021-07-23 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0057_auto_20210721_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.page')),
            ],
        ),
    ]
