# Generated by Django 3.2.5 on 2021-07-24 21:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder', '0058_checklistitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='EventItem',
        ),
        migrations.RenameField(
            model_name='repeatingoccurence',
            old_name='event',
            new_name='eventItem',
        ),
        migrations.RenameField(
            model_name='singleoccurence',
            old_name='event',
            new_name='eventItem',
        ),
    ]
