# Generated by Django 3.2.5 on 2021-07-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0059_auto_20210724_2105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageListing',
            new_name='PageInfo',
        ),
    ]
