# Generated by Django 3.2.5 on 2021-07-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0061_page_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinfo',
            name='defaultExplanation',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
