# Generated by Django 3.2.5 on 2021-07-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0062_pageinfo_defaultexplanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinfo',
            name='monoItemed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
