# Generated by Django 3.2.5 on 2021-07-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0063_pageinfo_monoitemed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='type',
        ),
    ]
