# Generated by Django 3.2.5 on 2021-07-26 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0064_remove_page_typee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageinfo',
            old_name='name',
            new_name='type',
        ),
    ]
