# Generated by Django 3.2.5 on 2021-07-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0066_rename_monoitemed_pageinfo_hassingleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorfield',
            name='label',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
