# Generated by Django 3.2.5 on 2021-07-29 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0067_colorfield_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='color',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.SET_DEFAULT, to='builder.colorfield'),
        ),
    ]
